import ProjectModel from "models/Project";

const projects: ProjectModel[] = [
  {
    id: 1,
    jobTitle: { en: "Android Developer", fa: "توسعه دهنده اندروید" },
    title: { en: "Zuperi App (Client side)", fa: "اپلیکیشن سمت مشتری زوپری" },
    from: new Date(2018, 8, 23),
    to: new Date(2019, 4, 21),
    companyId: 1,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 2,
    jobTitle: { en: "Android Developer", fa: "توسعه دهنده اندروید" },
    title: {
      en: "Zuperi App (SuperMarket side)",
      fa: "اپلیکیشن سمت سوپرمارکت دار زوپری",
    },
    from: new Date(2019, 4, 21),
    to: new Date(2019, 11, 22),
    companyId: 1,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 3,
    jobTitle: { en: "Android Developer", fa: "توسعه دهنده اندروید" },
    title: {
      en: "Besha App",
      fa: "اپلیکیشن بهسا",
    },
    from: new Date(2019, 11, 22),
    to: new Date(2020, 3, 19),
    companyId: 2,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 4,
    jobTitle: { en: "Android Developer", fa: "توسعه دهنده اندروید" },
    title: {
      en: "Maya App",
      fa: "اپلیکیشن مایا پخش",
    },
    from: new Date(2020, 1, 21),
    to: new Date(2020, 3, 19),
    companyId: 3,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 5,
    jobTitle: { en: "Android Developer", fa: "توسعه دهنده اندروید" },
    title: {
      en: "Driver App",
      fa: "اپلیکیشن رانندگان",
    },
    from: new Date(2020, 3, 10),
    to: new Date(2020, 4, 30),
    companyId: 3,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 6,
    jobTitle: { en: "Android Developer", fa: "توسعه دهنده اندروید" },
    title: {
      en: "Book App",
      fa: "اپلیکیشن کتاب صوتی (به نام کتاب)",
    },
    from: new Date(2020, 5, 1),
    to: new Date(2020, 5, 20),
    companyId: 3,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 7,
    jobTitle: {
      en: "Front End Developer (React Js)",
      fa: "برنامه نویس فرانت اند",
    },
    title: {
      en: "Ratin Ads",
      fa: "سایت مشتریان راتین",
    },
    from: new Date(2020, 7, 22),
    to: new Date(2021, 1, 20),
    companyId: 4,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 8,
    jobTitle: {
      en: "Front End Developer (React Js)",
      fa: "برنامه نویس فرانت اند",
    },
    title: {
      en: "Ratin Crm",
      fa: "سایت مدیریت مشتریان راتین",
    },
    from: new Date(2021, 1, 20),
    to: new Date(2021, 3, 19),
    companyId: 4,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 9,
    jobTitle: {
      en: "Front End Developer (React Js)",
      fa: "برنامه نویس فرانت اند",
    },
    title: {
      en: "Houshiz",
      fa: "بازی سوال و جوابی هوشیز",
    },
    from: new Date(2021, 1, 20),
    to: new Date(2021, 4, 21),
    companyId: 3,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  // {
  //   id: 10,
  //   jobTitle: {
  //     en: "Mobile Developer (React Native)",
  //     fa: "برنامه نویس سمت موبایل (ری اکت نیتیو)",
  //   },
  //   title: {
  //     en: "Bilimob",
  //     fa: "اپلیکیشن بیلیموب",
  //   },
  //   from: new Date(2021, 1, 20),
  //   to: new Date(2021, 4, 21),
  //   companyId: 5,
  //   shortDescription: { en: "salam", fa: "سلام" },
  //   description: { en: "", fa: "" },
  //   images: [{ image: "", title: "" }],
  // },
  {
    id: 11,
    jobTitle: {
      en: "Mobile Developer (React Native)",
      fa: "برنامه نویس سمت موبایل (ری اکت نیتیو)",
    },
    title: {
      en: "Mirorim",
      fa: "اپلیکیشن میروریم",
    },
    from: new Date(2021, 4, 21),
    to: new Date(2022, 3, 20),
    companyId: 6,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 12,
    jobTitle: {
      en: "Front End Developer (Next JS)",
      fa: "برنامه نویس فرانت اند",
    },
    title: {
      en: "Peteman",
      fa: "سایت پت من",
    },
    from: new Date(2021, 4, 21),
    to: new Date(2022, 3, 20),
    companyId: 6,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 13,
    jobTitle: {
      en: "Mobile Developer (React Native)",
      fa: "برنامه نویس سمت موبایل (ری اکت نیتیو)",
    },
    title: {
      en: "Mirorup",
      fa: "اپلیکیشن میرورآپ",
    },
    from: new Date(2021, 4, 21),
    to: new Date(2022, 3, 20),
    companyId: 6,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
  {
    id: 14,
    jobTitle: {
      en: "Front End Developer (React Js)",
      fa: "برنامه نویس فرانت اند",
    },
    title: {
      en: "باجه 724",
      fa: "سایت باجه 724",
    },
    from: new Date(2021, 8, 23),
    // to: new Date(),
    companyId: 7,
    shortDescription: { en: "salam", fa: "سلام" },
    description: { en: "", fa: "" },
    images: [{ image: "", title: "" }],
  },
];

export default projects;
